#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

set -e

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
WEBUI_PORTS=${WEBUI_PORTS}
----------------------------------------------------------------------
"

if [[ ! -f "${CONFIG_DIR}/config.toml" ]]; then
    log_inf "Generating default [${CONFIG_DIR}/config.toml] file."
    "${APP_DIR}/qui" generate-config --config-dir "${CONFIG_DIR}"
    find "${CONFIG_DIR}/config.toml" \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi
