#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
WEBUI_PORTS=${WEBUI_PORTS}
----------------------------------------------------------------------
"

if [[ ! -f "${CONFIG_DIR}/config.toml" ]]; then
    "${APP_DIR}/qui" generate-config --config-dir "${CONFIG_DIR}"
    find "${CONFIG_DIR}/config.toml" \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi
